### ISSUE TITLE
Gateway version 1.2.42: connection not working anymore

### ISSUE THREAD

**Issue by peterkappelt** [peterkappelt/Tradfri-FHEM#11]
Changes in DTLS handshake

Please do not update, otherwise this module won't work

**Comment by peterkappelt** [comment]
Solution is described here:

https://github.com/ggravlingen/pytradfri/issues/90

**Comment by Schockwelle** [comment]
Danke für den Hinweis.

Ich habe den Befehl ausgeführt und habe eine neuen Key. Die Abfrage der Devices über die Konsole funktioniert, aber nicht über FHEM obwohl ich den Key dort geändert habe.

Bei get devicelist über FHEM erhalten ich folgenden Fehler: Error while trying to fetch devices!

Mache ich etwas falsch bzw. muss das "IDENTITY" noch irgendwo hinterlegt werden?

**Comment by Schockwelle** [comment]
Habs jetzt selbst hinbekommen:

Replace in TradfriLib.pm:

my $coapClientCMD = "timeout 5s coap-client -u Client_identity -k $gwSecret -v 1 -m $method coaps://$gwAddress:5684/$path";

With:

my $coapClientCMD = "timeout 5s coap-client -u IDENTITY  -k $gwSecret -v 1 -m $method coaps://$gwAddress:5684/$path";

**Comment by peterkappelt** [comment]
(Supposedly) fixed for Beta with JTradfri buid 0.0.4

**Comment by peterkappelt** [comment]
Anleitung für Nutzer der Stable-Version mit coap-client/ manual for users of the stable version:
* Get a session key from the gateway by running this command on the command line of your system: ```coap-client -m post -u "Client_identity" -k "SECURITY_CODE" -e '{"9090":"IDENTITY"}' "coaps://IP_ADDRESS:5684/15011/9063"``` Replace IP_ADDRESS with the IP of your gateway and SECURITY_CODE with your PSK. There will be a return like this: ```{"9091":"YOUR_NEW_PSK","9029":"1.2.0042"}```
* Modify TradfriLib.pm as Schochwelle has described
* Set the PSK of your TradfriGateway in FHEM to YOUR_NEW_PSK, restart FHEM

This solution works - but it hasn't been tested for long. You might have to repeat this procedure in a couple of weeks, until a "real" fix is published.

**Comment by DanMittendorf** [comment]
I would like to reopen this as reported in #14  that this workaround/temporary fix isn't working anymore for at least two users (see #14  )

EDIT:
Nevermind! I used the wrong IP address... My bad! Sorry.
